ALTER TYPE "ReferenceEntityType" ADD VALUE 'PUBLISH_ATTEMPT';
ALTER TYPE "WorkflowJobType" ADD VALUE 'RENDER';
ALTER TYPE "WorkflowJobType" ADD VALUE 'PUBLISH';
ALTER TYPE "CostCategory" ADD VALUE 'RENDER';
ALTER TYPE "CostCategory" ADD VALUE 'PUBLISHING';
ALTER TYPE "AssetType" ADD VALUE 'VIDEO';
ALTER TYPE "AssetRole" ADD VALUE 'RENDER_OUTPUT';
