apiVersion: 1

policies:
  - orgId: 1
    receiver: videotik-alerting
    group_by:
      - alertname
      - pipeline
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: videotik-alerting
        object_matchers:
          - - severity
            - =
            - critical
        continue: true
      - receiver: videotik-alerting
        object_matchers:
          - - severity
            - =
            - warning
      - receiver: videotik-alerting
        object_matchers:
          - - pipeline
            - =
            - render
      - receiver: videotik-alerting
        object_matchers:
          - - pipeline
            - =
            - publish
